version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
#    volumes:
#      - ./loki-config.yaml:/mnt/config/loki-config.yaml
#    command: -config.file=/mnt/config/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3300:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - loki

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - loki
